# Generated by Django 2.2.7 on 2019-11-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191105_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(default=1, to='posts.Category', verbose_name='Category'),
        ),
    ]
